In [ ]:
#데이터 불러오기,데이터 합치기
import pandas as pd

df_bbc = pd.read_csv('dataset/BBC_NEWS.CSV', encoding='ISO-8859-1', names=['Date','Title','Url','Content','Google_noti','Xml_url'])
df_sbs = pd.read_csv('dataset/SBS_NEWS.CSV', encoding='cp949', names=['Date','Title','Url','Content','Google_noti','Xml_url'])  # Adjusted encoding to match the file's actual encoding

df_bbc.head(5)

,Date,Title,Url,Content,Google_noti,Xml_url
0,"March 24, 2025 at 09:50AM",BBC Press Office needs to clarify Blue Peter s...,https://cleanfeed.thetvroom.com/22559/opinion/...,A textbook example is unfolding of a self-infl...,Google ¾Ë¸®¹Ì - bbc,https://www.google.com/alerts/feeds/0409998130...
1,"March 24, 2025 at 10:38AM",BBC Radio 1 legend Andy Peebles dies as collea...,https://www.nottinghampost.com/news/celebs-tv/...,The DJ and presenter has died at the age of 76...,Google ¾Ë¸®¹Ì - bbc,https://www.google.com/alerts/feeds/0409998130...
2,"March 24, 2025 at 11:21AM",BBC in grovelling Scotland vs Greece apology o...,https://www.dailyrecord.co.uk/sport/football/f...,The Tartan Army tuning in for the first Hampde...,Google ¾Ë¸®¹Ì - bbc,https://www.google.com/alerts/feeds/0409998130...
3,"March 24, 2025 at 11:26AM",BBC reveal real reason stars haven't worked to...,https://www.express.co.uk/showbiz/tv-radio/203...,"<b>BBC</b> Today stars Nick Robinson, 61, and ...",Google ¾Ë¸®¹Ì - bbc,https://www.google.com/alerts/feeds/0409998130...
4,"March 24, 2025 at 12:47PM",Wynne Evans 'axed' from GoCompare ads amid BBC...,https://www.gbnews.com/celebrity/wynne-evans-g...,... <b>BBC</b> Strictly star&#39;s &#39;miscon...,Google ¾Ë¸®¹Ì - bbc,https://www.google.com/alerts/feeds/0409998130...

In [7]:
df_sbs.head(5)

,Date,Title,Url,Content,Google_noti,Xml_url
0,"March 24, 2025 at 01:10PM","최여진, 7세 연상 '돌싱' 예비 남편 논란 입 열까…""방송으로 확인"" [공식] -...",https://www.hankyung.com/article/2025032431187,... <b>SBS</b> &#39;동상이몽2-너는 내 운명&#39; 제작진이 방송...,Google 알리미 - sbs,https://www.google.com/alerts/feeds/0409998130...
1,"March 24, 2025 at 01:17PM","TREASURE(트레저) 'YELLOW', HIGHER 주간 SBS 인기가요 핫스테...",https://sports.khan.co.kr/article/202503241314003,제1260회 <b>SBS</b> 인기가요 핫스테이지 영광의 1위는 &#39;TREA...,Google 알리미 - sbs,https://www.google.com/alerts/feeds/0409998130...
2,"March 24, 2025 at 01:19PM","TREASURE(트레저) 'YELLOW', HIGHER 주간 SBS 인기가요 핫스테...",https://news.nate.com/view/20250324n19221?mid=...,한눈에 보는 오늘 : 연예가 화제 - 뉴스 : 사진제공 | HIGHER(하이어)제1...,Google 알리미 - sbs,https://www.google.com/alerts/feeds/0409998130...
3,"March 24, 2025 at 01:53PM","가수 최유리, SBS '애프터클럽' 새 DJ 합류 - 브릿지경제",https://www.viva100.com/article/20250324500598,가수 최유리가 <b>SBS</b> &#39;애프터클럽&#39;의 새 DJ로 찾아온다...,Google 알리미 - sbs,https://www.google.com/alerts/feeds/0409998130...
4,"March 24, 2025 at 06:18PM","한덕수 복귀하자 최상목 활짝 웃으며 ""드디어"" (현장영상) / SBS - YouTube",https://www.youtube.com/watch?v=7JS45Bp8bIc,... <b>sbs</b>.co.kr/y/t/?id=10000000121 #<b>S...,Google 알리미 - sbs,https://www.google.com/alerts/feeds/0409998130...

In [8]:
#결측치 확인,처리(bbc 데이터,sbs 데이터)
print(df_bbc.isnull().sum())
print(df_sbs.isnull().sum())

Date           0
Title          0
Url            0
Content        0
Google_noti    0
Xml_url        0
dtype: int64
Date           0
Title          0
Url            0
Content        0
Google_noti    0
Xml_url        0
dtype: int64

In [9]:
#중복 데이터 있는지 확인

print(df_sbs.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
dtype: bool

In [10]:
print(df_bbc.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [11]:
#HTML 태그, 특수문자 제거(bbc 데이터)
import re

def clean(text):
    """
    텍스트(문자열)에서 HTML 태그와 특수문자를 제거하는 함수, 중복된 공백을 단일 공백으로 정리한 뒤 반환 
    """
    # 1) HTML 태그 제거
    #    <...> 형태의 모든 문자열을 공백으로 치환
    text = re.sub(r'<[^>]+>', '', text)

    # 2) 불필요한 특수문자 제거
    #    여기서는 괄호, 특수기호, 이모티콘, 광고용 기호 등을 예시로 처리했습니다.
    #    필요에 따라 범위를 조정하세요.
    text = re.sub(r'[\(\)\[\]\{\}<>]', '', text)
    text = re.sub(r'[#@*■…▶▲△☆★]', '', text)

    # (선택) 알파벳, 숫자, 한글, 일반적인 문장부호 외의 모든 문자 제거
    #text = re.sub(r'[^a-zA-Z0-9가-힣\s.,!?]', '', text)

    # 3) 여러 개의 공백을 하나로 줄이기
    text = re.sub(r'\s+', ' ', text)

    # 앞뒤 공백 제거 후 반환
    return text.strip()

# df.select_dtypes(include='object')는 문자열(오브젝트) 타입 컬럼들만 골라냄
text_cols = df_bbc.select_dtypes(include='object').columns

for col in text_cols:
    df_bbc[col] = df_bbc[col].apply(clean)

df_bbc.head()
print(df_bbc.head)

<bound method NDFrame.head of                          Date  \
0   March 24, 2025 at 09:50AM
1   March 24, 2025 at 10:38AM
2   March 24, 2025 at 11:21AM
3   March 24, 2025 at 11:26AM
4   March 24, 2025 at 12:47PM
5   March 24, 2025 at 01:16PM
6   March 24, 2025 at 02:24PM
7   March 24, 2025 at 03:39PM
8   March 24, 2025 at 04:00PM
9   March 24, 2025 at 04:01PM
10  March 24, 2025 at 04:02PM
11  March 24, 2025 at 04:08PM
12  March 24, 2025 at 04:09PM
13  March 24, 2025 at 04:52PM
14  March 24, 2025 at 03:45PM
15  March 24, 2025 at 07:57PM
16  March 24, 2025 at 05:33PM
17  March 24, 2025 at 10:04PM
18  March 24, 2025 at 10:51PM
19  March 24, 2025 at 08:35PM
20  March 24, 2025 at 11:44PM
21  March 25, 2025 at 12:03AM
22  March 25, 2025 at 02:01AM
23  March 25, 2025 at 02:21AM
24  March 25, 2025 at 03:24AM
25  March 25, 2025 at 03:41AM
26  March 25, 2025 at 03:54AM
27  March 25, 2025 at 04:18AM
28  March 25, 2025 at 06:11AM
29  March 25, 2025 at 04:11AM
30  March 25, 2025 at 04:56AM
31  March 25, 2025 at 05:58AM

                                                Title  \
0   BBC Press Office needs to clarify Blue Peter s...
1   BBC Radio 1 legend Andy Peebles dies as collea...
2   BBC in grovelling Scotland vs Greece apology o...
3   BBC reveal real reason stars haven't worked to...
4   Wynne Evans 'axed' from GoCompare ads amid BBC...
5   BBC This City is Ours star Sean Bean makes spe...
6   BBC Radio 1 legend Andy Peebles dies suddenly ...
7   BBC forced into grovelling apology seconds int...
8   Former BBC Radio 1 DJ Andy Peebles dies aged 7...
9   The terrifying BBC hidden gem fans can't stop ...
10  BBC Radio 1 legend dead aged 76: Colleagues le...
11  Secret 'feud' as two BBC stars go 90 days with...
12  Andy Peebles death: BBC Radio 1 DJ behind John...
13  Clashing egos and scheduling headaches? Inside...
14  I've seen every Jane Austen adaptation - these...
15  US-Russia officials holding Ukraine talks in S...
16  Canada calls snap election to tackle Trump - Y...
17  How the world's largest underwater tunnel is b...
18  BBC axes live episodes of Blue Peter after 66 ...
19  The three-year-old girl who braids hair like a...
20  More than 1100 people arrested in Turkey durin...
21           BBC News & Views inside Europe - YouTube
22  Tate brothers report to Romania police after r...
23  Concerns over popularity of skin bleaching cre...
24  Smoggie Queens' Renewed For Season 2 By BBC - ...
25  Greenland condemns planned visits by Usha Vanc...
26  Zoe Ball's father says she's in 'a good place'...
27  BBC Making Liverpool Drama 'The Cage' With She...
28  Two women who spied for Russia tracked down an...
29  BBC star Steve Stamp rushed to hospital after ...
30  TV tonight: a painful but lovely film about th...
31  What's being discussed during Russia-US peace ...

                                                  Url  \
0   https://cleanfeed.thetvroom.com/22559/opinion/...
1   https://www.nottinghampost.com/news/celebs-tv/...
2   https://www.dailyrecord.co.uk/sport/football/f...
3   https://www.express.co.uk/showbiz/tv-radio/203...
4   https://www.gbnews.com/celebrity/wynne-evans-g...
5   https://www.liverpoolecho.co.uk/news/tv/bbc-ci...
6   https://www.thesun.co.uk/tvandshowbiz/33995841...
7   https://www.mirror.co.uk/sport/football/news/s...
8   https://www.rte.ie/entertainment/2025/0323/150...
9   https://www.dailymail.co.uk/tv/article-1451559...
10  https://www.dailymail.co.uk/news/article-14528...
11  https://www.thesun.co.uk/tvandshowbiz/33997738...
12  https://www.independent.co.uk/arts-entertainme...
13  https://www.telegraph.co.uk/radio/radio-presen...
14  https://inews.co.uk/culture/television/jane-au...
15        https://www.youtube.com/watch?v=ieFDaC8t9jU
16        https://www.youtube.com/watch?v=Vk2dzbcKO1c
17        https://www.youtube.com/watch?v=jm2ekl2agyM
18  https://www.independent.co.uk/bulletin/culture...
19        https://www.youtube.com/watch?v=rcYAg-9_Jf0
20        https://www.youtube.com/watch?v=ZuPKt63nsPU
21        https://www.youtube.com/watch?v=Pt-DOC3wpdo
22        https://www.youtube.com/watch?v=I-hrvULfPAo
23        https://www.youtube.com/watch?v=djTyHf-7oxo
24  https://deadline.com/2025/03/bbc-smoggie-queen...
25        https://www.youtube.com/watch?v=A8M0P6R51qA
26  https://www.independent.co.uk/arts-entertainme...
27  https://deadline.com/2025/03/bbc-the-cage-dram...
28     https://www.bbc.com/news/articles/cqx0v599wqvo
29  https://www.standard.co.uk/news/london/bbc-sta...
30  https://www.theguardian.com/tv-and-radio/2025/...
31        https://www.youtube.com/watch?v=B5suzRHMzTI

                                              Content          Google_noti  \
0   A textbook example is unfolding of a self-infl...  Google ¾Ë¸®¹Ì - bbc
1   The DJ and presenter has died at the age of 76...  Google ¾Ë¸®¹Ì - bbc
2   The Tartan Army tuning in for the first Hampde...  Google ¾Ë¸®¹Ì - bbc
3   BBC Today stars Nick Robinson, 61, and Emma Ba...  Google ¾Ë¸®¹Ì - bbc
4   ... BBC Strictly star&39;s &39;misconduct&39; ...  Google ¾Ë¸®¹Ì - bbc
5   The 65-year-old plays Ronnie Phelan in the eig...  Google ¾Ë¸®¹Ì - bbc
6   FORMER BBC Radio 1 DJ Andy Peebles, the final ...  Google ¾Ë¸®¹Ì - bbc
7   Scotland fans tuned into the BBC expecting liv...  Google ¾Ë¸®¹Ì - bbc
8   Former BBC Radio 1 DJ Andy Peebles, the final ...  Google ¾Ë¸®¹Ì - bbc
9   Horror fans have been left hooked by a BBC hid...  Google ¾Ë¸®¹Ì - bbc
10  BBC Radio 1 legend DJ Andy Peebles has died ag...  Google ¾Ë¸®¹Ì - bbc
11  Emma Barnett presenting BBC Radio 4 Today. 3. ...  Google ¾Ë¸®¹Ì - bbc
12  Peebles&39;s family confirmed the news of his ...  Google ¾Ë¸®¹Ì - bbc
13  Inside BBC Today&39;s presenting problem. With...  Google ¾Ë¸®¹Ì - bbc
14  The BBC&39;s 1995 &39;Pride and Prejudice&39; ...  Google ¾Ë¸®¹Ì - bbc
15  ... bbc.com/news Ukraine Russia BBCNews. ... U...  Google ¾Ë¸®¹Ì - bbc
16  ... Pardon. Preta Moraes New 1M views &middot;...  Google ¾Ë¸®¹Ì - bbc
17  ... bbc.com/news Denmark Fehmarnbelt BBCNews. ...  Google ¾Ë¸®¹Ì - bbc
18  The shift to pre-recorded episodes is attribut...  Google ¾Ë¸®¹Ì - bbc
19  ????? ??? ????? ?? ???? ????? ????? ??? ??? ??...  Google ¾Ë¸®¹Ì - bbc
20  ... bbc.com/news Turkey BBCNews. ... More than...  Google ¾Ë¸®¹Ì - bbc
21  Sara-Jayne Makwala King in for Clarence Ford i...  Google ¾Ë¸®¹Ì - bbc
22  British-American influencer Andrew Tate and hi...  Google ¾Ë¸®¹Ì - bbc
23  ... BBC&39;s Madina Maishanu has visited Kano ...  Google ¾Ë¸®¹Ì - bbc
24  BBC&39;s &39;Smoggie Queens&39; has been renew...  Google ¾Ë¸®¹Ì - bbc
25  Greenland&39;s politicians have condemned plan...  Google ¾Ë¸®¹Ì - bbc
26  Broadcaster stepped away from BBC Radio 2 Brea...  Google ¾Ë¸®¹Ì - bbc
27  The BBC is making a Liverpool drama &39;The Ca...  Google ¾Ë¸®¹Ì - bbc
28  Bulgarian nationals Cvetelina Gencheva and Tsv...  Google ¾Ë¸®¹Ì - bbc
29  A BBC star has warned of the dangers of drunk ...  Google ¾Ë¸®¹Ì - bbc
30  Love and Loss: The Pandemic 5 Years On on BBC ...  Google ¾Ë¸®¹Ì - bbc
31  ... BBC Sounds to play Newscast¡±. It works on...  Google ¾Ë¸®¹Ì - bbc

                                              Xml_url
0   https://www.google.com/alerts/feeds/0409998130...
1   https://www.google.com/alerts/feeds/0409998130...
2   https://www.google.com/alerts/feeds/0409998130...
3   https://www.google.com/alerts/feeds/0409998130...
4   https://www.google.com/alerts/feeds/0409998130...
5   https://www.google.com/alerts/feeds/0409998130...
6   https://www.google.com/alerts/feeds/0409998130...
7   https://www.google.com/alerts/feeds/0409998130...
8   https://www.google.com/alerts/feeds/0409998130...
9   https://www.google.com/alerts/feeds/0409998130...
10  https://www.google.com/alerts/feeds/0409998130...
11  https://www.google.com/alerts/feeds/0409998130...
12  https://www.google.com/alerts/feeds/0409998130...
13  https://www.google.com/alerts/feeds/0409998130...
14  https://www.google.com/alerts/feeds/0409998130...
15  https://www.google.com/alerts/feeds/0409998130...
16  https://www.google.com/alerts/feeds/0409998130...
17  https://www.google.com/alerts/feeds/0409998130...
18  https://www.google.com/alerts/feeds/0409998130...
19  https://www.google.com/alerts/feeds/0409998130...
20  https://www.google.com/alerts/feeds/0409998130...
21  https://www.google.com/alerts/feeds/0409998130...
22  https://www.google.com/alerts/feeds/0409998130...
23  https://www.google.com/alerts/feeds/0409998130...
24  https://www.google.com/alerts/feeds/0409998130...
25  https://www.google.com/alerts/feeds/0409998130...
26  https://www.google.com/alerts/feeds/0409998130...
27  https://www.google.com/alerts/feeds/0409998130...
28  https://www.google.com/alerts/feeds/0409998130...
29  https://www.google.com/alerts/feeds/0409998130...
30  https://www.google.com/alerts/feeds/0409998130...
31  https://www.google.com/alerts/feeds/0409998130...  >

In [12]:
#HTML 태그, 특수문자 제거(sbs 데이터)
# df.select_dtypes(include='object')는 문자열(오브젝트) 타입 컬럼들만 골라냄
text_cols = df_bbc.select_dtypes(include='object').columns

for col in text_cols:
    df_sbs[col] = df_sbs[col].apply(clean)

df_sbs.head()
print(df_sbs.head)

<bound method NDFrame.head of                          Date  \
0   March 24, 2025 at 01:10PM
1   March 24, 2025 at 01:17PM
2   March 24, 2025 at 01:19PM
3   March 24, 2025 at 01:53PM
4   March 24, 2025 at 06:18PM
5   March 24, 2025 at 07:03PM
6   March 24, 2025 at 03:07PM
7   March 24, 2025 at 03:20PM
8   March 24, 2025 at 05:19PM
9   March 24, 2025 at 05:34PM
10  March 24, 2025 at 08:23PM
11  March 24, 2025 at 08:55PM
12  March 24, 2025 at 09:22PM
13  March 24, 2025 at 09:37PM
14  March 24, 2025 at 08:51PM
15  March 24, 2025 at 09:44PM
16  March 24, 2025 at 10:23PM
17  March 24, 2025 at 10:28PM
18  March 25, 2025 at 12:01AM
19  March 25, 2025 at 12:28AM
20  March 25, 2025 at 12:30AM
21  March 25, 2025 at 12:49AM
22  March 25, 2025 at 12:58AM
23  March 25, 2025 at 01:07AM
24  March 25, 2025 at 01:20AM
25  March 24, 2025 at 08:50PM
26  March 24, 2025 at 09:16PM
27  March 24, 2025 at 10:25PM
28  March 25, 2025 at 02:56AM
29  March 25, 2025 at 03:15AM
30  March 25, 2025 at 03:25AM
31  March 25, 2025 at 06:06AM
32  March 25, 2025 at 06:21AM
33  March 25, 2025 at 06:29AM
34  March 25, 2025 at 06:34AM
35  March 25, 2025 at 06:34AM
36  March 25, 2025 at 06:35AM
37  March 25, 2025 at 06:35AM
38  March 25, 2025 at 06:41AM
39  March 25, 2025 at 06:44AM
40  March 25, 2025 at 06:46AM
41  March 25, 2025 at 06:51AM
42  March 25, 2025 at 07:23AM
43  March 25, 2025 at 07:23AM
44  March 25, 2025 at 07:31AM
45  March 25, 2025 at 07:46AM
46  March 25, 2025 at 07:52AM

                                                Title  \
0    최여진, 7세 연상 '돌싱' 예비 남편 논란 입 열까"방송으로 확인" 공식 - 한국경제
1   TREASURE트레저 'YELLOW', HIGHER 주간 SBS 인기가요 핫스테이지...
2   TREASURE트레저 'YELLOW', HIGHER 주간 SBS 인기가요 핫스테이지...
3                 가수 최유리, SBS '애프터클럽' 새 DJ 합류 - 브릿지경제
4      한덕수 복귀하자 최상목 활짝 웃으며 "드디어" 현장영상 / SBS - YouTube
5      중동 다시 확전이스라엘군 지상군 작전 확대 / SBS / D리포트 - YouTube
6             현장영상 한덕수 복귀하자 최상목 활짝 웃으며 "드디어" - SBS 뉴스
7   술 취한 거 아닌데 10km를 역주행한 차량, "실형 가능성 높은 범죄 행위" 현장...
8   "한국은 1억 개 보내" 미국 요구"국내 가격도 심상치 않은데" 난색 자막뉴스 / SBS
9                  직장인만 서럽겠네'지역가입자 건보료만 '뚝' - SBS Biz
10  "한덕수 재탄핵" 목소리까지'마은혁 임명 언제?" 묻자 / SBS 특집 8뉴스 - ...
11  현장 꺼질 기미가 보이지 않는다오히려 번지고 있는 산불 상황 / SBS 특집 8뉴스...
12  의대생들에 날아간 '제적 통보서'"두려워 복귀" VS "설마 하겠어?" / SBS ...
13  나홀로 인용, 2명은 '각하'헌법재판관들의 판단 이유는 / SBS 특집 8뉴스 - ...
14       장나라 "남편, SBS 연기대상 받은 날 데리러 와차에서 오열" - 네이트 뉴스
15  윤 대통령 탄핵 심판 '힌트'? "예측 불가" 단서는 없었다 / SBS 특집 8뉴스...
16  의원 때리면 5년 국민 때리면 2년?....'사람 차별하냐' 묻자 '발끈'한 장경태...
17       날씨 강원 산지·동해안 등 강풍내일도 미세먼지 나쁨 / SBS - YouTube
18     골목길에서 잡힌 재수생"왜 그랬어요?" 묻자 / SBS / 오클릭 - YouTube
19  8명 중 유일한 '인용' 정계선 "한덕수, 모순적 국정 운영" / SBS 특집 8뉴...
20  "너무 똑같아서" 눈물이 왈칵AI로 생생히 그려내는 감동 / SBS / 모아보는 뉴...
21  활짝 웃은 최상목 "아, 드디어!"돌아온 한덕수 "이제 좌우는 없다" / SBS 특...
22   카페·편의점서 '삑''디지털 화폐' 실험 돌입 / SBS 특집 8뉴스 - YouTube
23  "이런 나라에서 배지가 무슨 의미야!" 이언주 '총사퇴' 발언에...국민의힘 줄줄이...
24  산불로 난리 난 상황인데"그럼 집에 가냐?" 골프 샷 / SBS / 오클릭 - Yo...
25          장나라 "남편, SBS 연기대상 받은 날 데리러 와차에서 오열" - 뉴스1
26                  TV SBS 오디션 프로젝트 `우리들의 발라드` - 매일신문
27        메가MGC커피, '2025 SBS 메가 콘서트' 2차 티켓 이벤트 - 시장경제
28            국내외 망신 '어쩌다 이런 일이''한국어능력시험 먹통 - SBS Biz
29   산불 키운 고온·건조·강풍하루하루 더 심해진다 / SBS 특집 8뉴스 - YouTube
30  한덕수 탄핵안 기각'비상계엄 선포 공모' 인정 안 돼 / SBS 특집 8뉴스 - Y...
31  "자기 순번도 아닌데.." 눈물당직 바꿔주고 갔다가 참변 / SBS 특집 8뉴스 -...
32                     모닝와이드 오늘의 주요뉴스 / SBS - YouTube
33        울주군 산불 나흘째오늘25일 오전 진화 '총력전' / SBS - YouTube
34      한덕수 탄핵소추 기각기각 5 · 인용 1 · 각하 2 / SBS - YouTube
35           강풍 타고 안동까지 번져국가동원령 추가 발령 / SBS - YouTube
36          진화율 85%, 오늘이 최대 고비이 시각 산청 / SBS - YouTube
37          비상계엄 적법성 · 내란죄 철회' 판단 없었다 / SBS - YouTube
38          땅 속으로 빨려 들어가듯'땅 꺼짐' 1명 실종 / SBS - YouTube
39             87일 만에 직무 복귀트럼프와 통화 추진 / SBS - YouTube
40          관세 '예외 시사'에 반색미국 증시 일제 상승 / SBS - YouTube
41        날씨 전국 초미세먼지충청 이남 산불 위기경보 심각 / SBS - YouTube
42          진화율 88%' 오늘이 최대 고비이 시각 산청 / SBS - YouTube
43        연세대 의대 45% '제적 예정'"구제책은 없다" / SBS - YouTube
44              울주군 산불 나흘째오전 진화에 '총력' / SBS - YouTube
45           휴전 회담 중에도 서로 공습민간인 피해 속출 / SBS - YouTube
46          카페·편의점서 '삑''디지털 화폐' 실험 착수 / SBS - YouTube

                                                  Url  \
0      https://www.hankyung.com/article/2025032431187
1   https://sports.khan.co.kr/article/202503241314003
2   https://news.nate.com/view/20250324n19221?mid=...
3      https://www.viva100.com/article/20250324500598
4         https://www.youtube.com/watch?v=7JS45Bp8bIc
5         https://www.youtube.com/watch?v=JqU44SVUWfI
6   https://news.sbs.co.kr/news/endPage.do?news_id...
7         https://www.youtube.com/watch?v=puX4qBCgZEA
8         https://www.youtube.com/watch?v=zvwHSJE1PyE
9           https://biz.sbs.co.kr/article/20000224295
10        https://www.youtube.com/watch?v=xLRv17u49-Q
11        https://www.youtube.com/watch?v=3t0XNgC1kZg
12        https://www.youtube.com/watch?v=ZFzuB2otxIE
13        https://www.youtube.com/watch?v=8u409lkxPeM
14          https://news.nate.com/view/20250324n38404
15        https://www.youtube.com/watch?v=eGDhQ1iw8OI
16        https://www.youtube.com/watch?v=666ia09CpcI
17        https://www.youtube.com/watch?v=y3GebLafVeA
18        https://www.youtube.com/watch?v=pjjsChY9c8E
19        https://www.youtube.com/watch?v=xHWoXbbc9rk
20        https://www.youtube.com/watch?v=-0hlIWaPvsk
21        https://www.youtube.com/watch?v=4R8NlJ58OtM
22        https://www.youtube.com/watch?v=wEO8gqfBJX4
23        https://www.youtube.com/watch?v=PKuP7WnTI7s
24        https://www.youtube.com/watch?v=JL1BnE32NRs
25  https://www.news1.kr/entertain/broadcast-tv/57...
26  https://www.imaeil.com/page/view/2025031717540...
27  https://www.meconomynews.com/news/articleView....
28          https://biz.sbs.co.kr/article/20000224458
29        https://www.youtube.com/watch?v=CQLgbO8vTMs
30        https://www.youtube.com/watch?v=Ne2mF9_6T2g
31        https://www.youtube.com/watch?v=Q3xBoAJvO4A
32        https://www.youtube.com/watch?v=XaGSwHuP9PA
33        https://www.youtube.com/watch?v=0RyZ866aysA
34        https://www.youtube.com/watch?v=se54nxn_oyU
35        https://www.youtube.com/watch?v=neClyNXNcEY
36        https://www.youtube.com/watch?v=R19ULww3k1s
37        https://www.youtube.com/watch?v=jvGNIB1jPuw
38        https://www.youtube.com/watch?v=NbN82Jwbnp8
39        https://www.youtube.com/watch?v=02QyCfVHgI8
40        https://www.youtube.com/watch?v=8wQ6NCxPQkg
41        https://www.youtube.com/watch?v=mC5vQWXReVE
42        https://www.youtube.com/watch?v=Wp2YOmdgLb8
43        https://www.youtube.com/watch?v=QjBVUZ2hpvA
44        https://www.youtube.com/watch?v=W9vHZppDuVQ
45        https://www.youtube.com/watch?v=biSmsQXLtTc
46        https://www.youtube.com/watch?v=mL1SuSI7nWY

                                              Content       Google_noti  \
0   ... SBS &39;동상이몽2-너는 내 운명&39; 제작진이 방송 확인을 당부했다...  Google 알리미 - sbs
1   제1260회 SBS 인기가요 핫스테이지 영광의 1위는 &39;TREASURE트레저&...  Google 알리미 - sbs
2   한눈에 보는 오늘 : 연예가 화제 - 뉴스 : 사진제공 | HIGHER하이어제126...  Google 알리미 - sbs
3   가수 최유리가 SBS &39;애프터클럽&39;의 새 DJ로 찾아온다. 24일 SBS...  Google 알리미 - sbs
4   ... sbs.co.kr/y/t/?id=10000000121 SBS뉴스 뉴스영상 총...  Google 알리미 - sbs
5   ... sbs.co.kr/y/?id=N1008033533 ☞이스라엘-팔레스타인 전쟁...  Google 알리미 - sbs
6   최상목 권한대행의 반응, 바로이뉴스에 담았습니다. 구성 : 조지현, 영상편집 : 이...  Google 알리미 - sbs
7   ... sbs.co.kr 문자 누르고 6000 전화: 02-2113-6000 홈페이...  Google 알리미 - sbs
8   ... sbs.co.kr/y/t/?id=10000000121 SBS뉴스 뉴스영상 미...  Google 알리미 - sbs
9   건강보험 지역가입자가 떠안은 보험료 부담 수준이 당국의 잇단 보험료 부담 완화 조치...  Google 알리미 - sbs
10  ... SBS에 &quot;한 대행이 두 재판관 임명을 문제 삼지 않을 걸로 안다&...  Google 알리미 - sbs
11  ... sbs.co.kr/y/?id=N1008033648 SBS뉴스 8뉴스 의성 산...  Google 알리미 - sbs
12  ... sbs.co.kr/y/i/?id=10000057872 SBS뉴스 8뉴스 의대...  Google 알리미 - sbs
13  ... sbs.co.kr/y/?id=N1008033634 SBS뉴스 8뉴스 대통령 ...  Google 알리미 - sbs
14  한편 장나라는 정하철 촬영감독과 2년 열애 끝에 지난 2022년 결혼식을 올렸다. ...  Google 알리미 - sbs
15  ... sbs.co.kr/y/i/?id=10000058872 SBS뉴스 8뉴스 윤대...  Google 알리미 - sbs
16  ... sbs.co.kr/y/t/?id=10000000121 SBS뉴스 뉴스영상 회...  Google 알리미 - sbs
17  ... sbs.co.kr/y/?id=N1008033423 ☞오늘의 날씨 기사 모아보...  Google 알리미 - sbs
18  ://news.sbs.co.kr/y/t/?id=10000000168 SBS뉴스 오클...  Google 알리미 - sbs
19  ... sbs.co.kr/y/?id=N1008033632 SBS뉴스 8뉴스 총리 한...  Google 알리미 - sbs
20  ... SBS 뉴스로 제보해주세요 홈페이지: https://news.sbs.co.k...  Google 알리미 - sbs
21  ... sbs.co.kr/y/?id=N1008033637 SBS뉴스 8뉴스 대통령 ...  Google 알리미 - sbs
22  ... sbs.co.kr/y/?id=N1008033665 SBS뉴스 8뉴스 실험 디...  Google 알리미 - sbs
23  ... sbs.co.kr/live ▷SBS 뉴스 제보하기 홈페이지: https://...  Google 알리미 - sbs
24  ... sbs.co.kr/y/?id=N1008033351 ☞오!클릭 기사 모아보기 ...  Google 알리미 - sbs
25  장나라 &quot;남편, SBS 연기대상 받은 날 데리러 와차에서 오열&quot;....  Google 알리미 - sbs
26  &39;우리들의 발라드&39;는 악뮤, 정승환, 비비, 카더가든 등을 발굴한 &39...  Google 알리미 - sbs
27  메가MGC커피가 오는 4월 9일까지 공식 애플리케이션앱에서 &39;2025 SBS ...  Google 알리미 - sbs
28  Copyright C SBS Medianet &amp; SBSi. All right...  Google 알리미 - sbs
29  ... sbs.co.kr/y/?id=N1008033661 SBS뉴스 8뉴스 바람 산...  Google 알리미 - sbs
30  ... sbs.co.kr/y/?id=N1008033631 SBS뉴스 8뉴스 재판관 ...  Google 알리미 - sbs
31  ... sbs.co.kr/y/i/?id=10000056672 SBS뉴스 8뉴스 TV...  Google 알리미 - sbs
32  ... sbs.co.kr/y/?id=N1008033912 SBS뉴스 모닝와이드 의성...  Google 알리미 - sbs
33  ... sbs.co.kr/y/?id=N1008033889 SBS뉴스 모닝와이드 바람...  Google 알리미 - sbs
34  ... sbs.co.kr/y/?id=N1008033891 SBS뉴스 모닝와이드 기각...  Google 알리미 - sbs
35  ... sbs.co.kr/y/?id=N1008033887 SBS뉴스 모닝와이드 산불...  Google 알리미 - sbs
36  ... sbs.co.kr/y/?id=N1008033888 SBS뉴스 모닝와이드 진화...  Google 알리미 - sbs
37  ... sbs.co.kr/y/i/?id=10000058872 SBS뉴스 모닝와이드 ...  Google 알리미 - sbs
38  ... sbs.co.kr/y/?id=N1008033890 SBS뉴스 모닝와이드 강동...  Google 알리미 - sbs
39  ... sbs.co.kr/y/?id=N1008033893 SBS뉴스 모닝와이드 기각...  Google 알리미 - sbs
40  ... sbs.co.kr/y/i/?id=10000059073 SBS뉴스 모닝와이드 ...  Google 알리미 - sbs
41  ... sbs.co.kr ▷SBS 뉴스 라이브 : https://n.sbs.co.k...  Google 알리미 - sbs
42  ... sbs.co.kr/y/i/?id=10000058372 SBS뉴스 화재 산불 ...  Google 알리미 - sbs
43  ... sbs.co.kr/y/?id=N1008033929 ☞의대 증원 기사 모아보기...  Google 알리미 - sbs
44  ... sbs.co.kr/y/i/?id=10000058372 SBS뉴스 울산 울주 ...  Google 알리미 - sbs
45  ... sbs.co.kr/y/i/?id=10000053472 SBS뉴스 러시아 우크...  Google 알리미 - sbs
46  ... sbs.co.kr/y/?id=N1008034001 SBS뉴스 실시간 디지털화...  Google 알리미 - sbs

                                              Xml_url
0   https://www.google.com/alerts/feeds/0409998130...
1   https://www.google.com/alerts/feeds/0409998130...
2   https://www.google.com/alerts/feeds/0409998130...
3   https://www.google.com/alerts/feeds/0409998130...
4   https://www.google.com/alerts/feeds/0409998130...
5   https://www.google.com/alerts/feeds/0409998130...
6   https://www.google.com/alerts/feeds/0409998130...
7   https://www.google.com/alerts/feeds/0409998130...
8   https://www.google.com/alerts/feeds/0409998130...
9   https://www.google.com/alerts/feeds/0409998130...
10  https://www.google.com/alerts/feeds/0409998130...
11  https://www.google.com/alerts/feeds/0409998130...
12  https://www.google.com/alerts/feeds/0409998130...
13  https://www.google.com/alerts/feeds/0409998130...
14  https://www.google.com/alerts/feeds/0409998130...
15  https://www.google.com/alerts/feeds/0409998130...
16  https://www.google.com/alerts/feeds/0409998130...
17  https://www.google.com/alerts/feeds/0409998130...
18  https://www.google.com/alerts/feeds/0409998130...
19  https://www.google.com/alerts/feeds/0409998130...
20  https://www.google.com/alerts/feeds/0409998130...
21  https://www.google.com/alerts/feeds/0409998130...
22  https://www.google.com/alerts/feeds/0409998130...
23  https://www.google.com/alerts/feeds/0409998130...
24  https://www.google.com/alerts/feeds/0409998130...
25  https://www.google.com/alerts/feeds/0409998130...
26  https://www.google.com/alerts/feeds/0409998130...
27  https://www.google.com/alerts/feeds/0409998130...
28  https://www.google.com/alerts/feeds/0409998130...
29  https://www.google.com/alerts/feeds/0409998130...
30  https://www.google.com/alerts/feeds/0409998130...
31  https://www.google.com/alerts/feeds/0409998130...
32  https://www.google.com/alerts/feeds/0409998130...
33  https://www.google.com/alerts/feeds/0409998130...
34  https://www.google.com/alerts/feeds/0409998130...
35  https://www.google.com/alerts/feeds/0409998130...
36  https://www.google.com/alerts/feeds/0409998130...
37  https://www.google.com/alerts/feeds/0409998130...
38  https://www.google.com/alerts/feeds/0409998130...
39  https://www.google.com/alerts/feeds/0409998130...
40  https://www.google.com/alerts/feeds/0409998130...
41  https://www.google.com/alerts/feeds/0409998130...
42  https://www.google.com/alerts/feeds/0409998130...
43  https://www.google.com/alerts/feeds/0409998130...
44  https://www.google.com/alerts/feeds/0409998130...
45  https://www.google.com/alerts/feeds/0409998130...
46  https://www.google.com/alerts/feeds/0409998130...  >

In [13]:
df_sbs['Content']

0     ... SBS &39;동상이몽2-너는 내 운명&39; 제작진이 방송 확인을 당부했다...
1     제1260회 SBS 인기가요 핫스테이지 영광의 1위는 &39;TREASURE트레저&...
2     한눈에 보는 오늘 : 연예가 화제 - 뉴스 : 사진제공 | HIGHER하이어제126...
3     가수 최유리가 SBS &39;애프터클럽&39;의 새 DJ로 찾아온다. 24일 SBS...
4     ... sbs.co.kr/y/t/?id=10000000121 SBS뉴스 뉴스영상 총...
5     ... sbs.co.kr/y/?id=N1008033533 ☞이스라엘-팔레스타인 전쟁...
6     최상목 권한대행의 반응, 바로이뉴스에 담았습니다. 구성 : 조지현, 영상편집 : 이...
7     ... sbs.co.kr 문자 누르고 6000 전화: 02-2113-6000 홈페이...
8     ... sbs.co.kr/y/t/?id=10000000121 SBS뉴스 뉴스영상 미...
9     건강보험 지역가입자가 떠안은 보험료 부담 수준이 당국의 잇단 보험료 부담 완화 조치...
10    ... SBS에 &quot;한 대행이 두 재판관 임명을 문제 삼지 않을 걸로 안다&...
11    ... sbs.co.kr/y/?id=N1008033648 SBS뉴스 8뉴스 의성 산...
12    ... sbs.co.kr/y/i/?id=10000057872 SBS뉴스 8뉴스 의대...
13    ... sbs.co.kr/y/?id=N1008033634 SBS뉴스 8뉴스 대통령 ...
14    한편 장나라는 정하철 촬영감독과 2년 열애 끝에 지난 2022년 결혼식을 올렸다. ...
15    ... sbs.co.kr/y/i/?id=10000058872 SBS뉴스 8뉴스 윤대...
16    ... sbs.co.kr/y/t/?id=10000000121 SBS뉴스 뉴스영상 회...
17    ... sbs.co.kr/y/?id=N1008033423 ☞오늘의 날씨 기사 모아보...
18    ://news.sbs.co.kr/y/t/?id=10000000168 SBS뉴스 오클...
19    ... sbs.co.kr/y/?id=N1008033632 SBS뉴스 8뉴스 총리 한...
20    ... SBS 뉴스로 제보해주세요 홈페이지: https://news.sbs.co.k...
21    ... sbs.co.kr/y/?id=N1008033637 SBS뉴스 8뉴스 대통령 ...
22    ... sbs.co.kr/y/?id=N1008033665 SBS뉴스 8뉴스 실험 디...
23    ... sbs.co.kr/live ▷SBS 뉴스 제보하기 홈페이지: https://...
24    ... sbs.co.kr/y/?id=N1008033351 ☞오!클릭 기사 모아보기 ...
25    장나라 &quot;남편, SBS 연기대상 받은 날 데리러 와차에서 오열&quot;....
26    &39;우리들의 발라드&39;는 악뮤, 정승환, 비비, 카더가든 등을 발굴한 &39...
27    메가MGC커피가 오는 4월 9일까지 공식 애플리케이션앱에서 &39;2025 SBS ...
28    Copyright C SBS Medianet &amp; SBSi. All right...
29    ... sbs.co.kr/y/?id=N1008033661 SBS뉴스 8뉴스 바람 산...
30    ... sbs.co.kr/y/?id=N1008033631 SBS뉴스 8뉴스 재판관 ...
31    ... sbs.co.kr/y/i/?id=10000056672 SBS뉴스 8뉴스 TV...
32    ... sbs.co.kr/y/?id=N1008033912 SBS뉴스 모닝와이드 의성...
33    ... sbs.co.kr/y/?id=N1008033889 SBS뉴스 모닝와이드 바람...
34    ... sbs.co.kr/y/?id=N1008033891 SBS뉴스 모닝와이드 기각...
35    ... sbs.co.kr/y/?id=N1008033887 SBS뉴스 모닝와이드 산불...
36    ... sbs.co.kr/y/?id=N1008033888 SBS뉴스 모닝와이드 진화...
37    ... sbs.co.kr/y/i/?id=10000058872 SBS뉴스 모닝와이드 ...
38    ... sbs.co.kr/y/?id=N1008033890 SBS뉴스 모닝와이드 강동...
39    ... sbs.co.kr/y/?id=N1008033893 SBS뉴스 모닝와이드 기각...
40    ... sbs.co.kr/y/i/?id=10000059073 SBS뉴스 모닝와이드 ...
41    ... sbs.co.kr ▷SBS 뉴스 라이브 : https://n.sbs.co.k...
42    ... sbs.co.kr/y/i/?id=10000058372 SBS뉴스 화재 산불 ...
43    ... sbs.co.kr/y/?id=N1008033929 ☞의대 증원 기사 모아보기...
44    ... sbs.co.kr/y/i/?id=10000058372 SBS뉴스 울산 울주 ...
45    ... sbs.co.kr/y/i/?id=10000053472 SBS뉴스 러시아 우크...
46    ... sbs.co.kr/y/?id=N1008034001 SBS뉴스 실시간 디지털화...
Name: Content, dtype: object

In [14]:
#텍스트 데이터 이상치 확인)-bbc 데이터

#(1) 문서 길이 기준
df_bbc['Content_len'] = df_bbc['Content'].apply(len)

# length 통계치 확인
print(df_bbc['Content_len'].describe())

# 길이가 50인 데이터 확인
# Content 열의 길이가 50인 데이터 필터링

# 몇 건이 이쓰지, 어떤 내용인지 확인, 무작위로 샘플 행 확인!
filtered_data = df_bbc[df_bbc['Content_len'] == 50]

print("길이가 50자만 있는 기사 수:", len(filtered_data))
print(filtered_data[['Content', 'Content_len']])  # 필요한 컬럼만 보기
print(filtered_data['Content'].values[0])

count     32.000000
mean     137.312500
std       26.495815
min       50.000000
25%      121.750000
50%      146.000000
75%      153.000000
max      175.000000
Name: Content_len, dtype: float64
길이가 50자만 있는 기사 수: 1
                                              Content  Content_len
30  Love and Loss: The Pandemic 5 Years On on BBC ...           50
Love and Loss: The Pandemic 5 Years On on BBC One.

In [15]:
#텍스트 데이터 이상치 확인)-sbs 데이터

#(1) 문서 길이 기준
df_sbs['Content_len'] = df_sbs['Content'].apply(len)

# length 통계치 확인
print(df_sbs['Content_len'].describe())

# 길이가 79인 데이터 확인
# Content 열의 길이가 79인 데이터 필터링

# 몇 건이 이쓰지, 어떤 내용인지 확인, 무작위로 샘플 행 확인!
filtered_data = df_sbs[df_sbs['Content_len'] == 79]

print("길이가 79자만 있는 기사 수:", len(filtered_data))
print(filtered_data[['Content', 'Content_len']])  # 필요한 컬럼만 보기
print(filtered_data['Content'].values[0])

count     47.000000
mean     117.595745
std       10.180244
min       79.000000
25%      113.000000
50%      119.000000
75%      121.500000
max      141.000000
Name: Content_len, dtype: float64
길이가 79자만 있는 기사 수: 1
                                             Content  Content_len
9  건강보험 지역가입자가 떠안은 보험료 부담 수준이 당국의 잇단 보험료 부담 완화 조치...           79
건강보험 지역가입자가 떠안은 보험료 부담 수준이 당국의 잇단 보험료 부담 완화 조치로 최근 5년 새 최저 수준으로 떨어진 것으로 나타났습니다.

# 영어 텍스틎 전처리:토큰화,불용어 제거(bbc 데이터)

In [11]:
# 영어 텍스틎 전처리:토큰화,불용어 제거(bbc 데이터)
! pip uninstall nltk
! pip install nltk

^C
Requirement already satisfied: nltk in c:\users\lg\appdata\local\programs\python\python310\lib\site-packages (3.9.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\lg\appdata\local\programs\python\python310\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: click in c:\users\lg\appdata\local\programs\python\python310\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: tqdm in c:\users\lg\appdata\local\programs\python\python310\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: joblib in c:\users\lg\appdata\local\programs\python\python310\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: colorama in c:\users\lg\appdata\local\programs\python\python310\lib\site-packages (from click->nltk) (0.4.6)

WARNING: You are using pip version 21.2.3; however, version 25.0.1 is available.
You should consider upgrading via the 'C:\Users\LG\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [1]:
import nltk
from  nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import string

nltk.download('punkt')
nltk.download('stopwords')
#필요하 리소스 다운로드(최초 1회만 실행)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LG\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LG\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [1]:
import nltk

# 다운받은 리소스 초기화 (혹시 꼬였을 경우 대비)
nltk.data.path.clear()

In [2]:
#다운로드는 되었지만 경로를 못 찾을 떄 
import nltk
from  nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# 수동으로 다운로드 경로를 지정 (사용자 폴더에 nltk_data 생성 후)
nltk.data.path.append("D:/기계학습 전처리/nltk_data")  # 본인 경로에 맞게 수정 가능

# punkt 다시 다운로드 시도
nltk.download('punkt', download_dir="D:/기계학습 전처리/nltk_data")
nltk.download('stopwords', download_dir="D:/기계학습 전처리/nltk_data")

[nltk_data] Downloading package punkt to D:/기계학습 전처리/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to D:/기계학습 전처리/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
from nltk.tokenize import word_tokenize
import nltk

print(nltk.data.path)  # NLTK가 리소스를 찾는 경로 리스트 확인

['D:/기계학습 전처리/nltk_data']

In [17]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LG\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [21]:
#전처리 함수 정의
from nltk.corpus import stopwords as nltk_stopwords
import string

stopwords = set(nltk_stopwords.words('english'))
punctuations = set(string.punctuation)

def preprocess_english(text):
    if not isinstance(text, str):
        return []
    
    # 1.소문자 변환
    text = text.lower()
    # 2.토큰화
    #tokens = word_tokenize(text)
    tokens = text.split()
    # 3. 불용어, 문장 부호 제거
    tokens = [token for token in tokens if token not in stopwords and token not in punctuations]

    return tokens

# bbc 뉴스 데이터 적용: Content 열에 대해 전처리 수행
df_bbc['Content_tokens'] = df_bbc['Content'].apply(preprocess_english)

#결과 확인
print(df_bbc[['Content', 'Content_tokens']].head(5))

                                             Content  \
0  A textbook example is unfolding of a self-infl...
1  The DJ and presenter has died at the age of 76...
2  The Tartan Army tuning in for the first Hampde...
3  BBC Today stars Nick Robinson, 61, and Emma Ba...
4  ... BBC Strictly star&39;s &39;misconduct&39; ...

                                      Content_tokens
0  [textbook, example, unfolding, self-inflicted,...
1  [dj, presenter, died, age, 76,, friends, colle...
2  [tartan, army, tuning, first, hampden, match, ...
3  [bbc, today, stars, nick, robinson,, 61,, emma...
4  [..., bbc, strictly, star&39;s, &39;misconduct...

In [29]:
# DataFrame을 CSV 파일로 저장
df_bbc.to_csv('bbc_preproces.csv', index=False, encoding='ISO-8859-1')

# 형태소 분석,불용어 제거(sbs 데이터)

In [ ]:
# 1. 라이브러리 설치 (최초 한 번만 실행)
#! pip install konlpy

Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
Requirement already satisfied: numpy>=1.6 in c:\users\lg\appdata\local\programs\python\python310\lib\site-packages (from konlpy) (2.0.2)
Collecting JPype1>=0.7.0
  Downloading jpype1-1.5.2-cp310-cp310-win_amd64.whl (356 kB)
Collecting lxml>=4.1.0
  Downloading lxml-5.3.1-cp310-cp310-win_amd64.whl (3.8 MB)
Requirement already satisfied: packaging in c:\users\lg\appdata\local\programs\python\python310\lib\site-packages (from JPype1>=0.7.0->konlpy) (24.1)
Installing collected packages: lxml, JPype1, konlpy
Successfully installed JPype1-1.5.2 konlpy-0.6.0 lxml-5.3.1

WARNING: You are using pip version 21.2.3; however, version 25.0.1 is available.
You should consider upgrading via the 'C:\Users\LG\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [ ]:
# 2. 라이브러리 불러오기
from konlpy.tag import Okt

# 3. 분석기 생성
okt = Okt()

# 4. 형태소 분석 함수 정의
def tokenize_text(text):
    if not isinstance(text, str):  # NaN 또는 숫자 예외 처리
        return []
    return okt.morphs(text, stem=True)  # stem=True: 어간 추출 (예: '합니다' → '하다')

In [ ]:
# 5. 전체 데이터에 적용 (예: content 컬럼에 형태소 분석 적용)
df_bbc['tokens'] = df_bbc['Content'].apply(tokenize_text)

In [ ]:
# 6. 불용어 사전 정의
stopwords = [
    '은', '는', '이', '가', '을', '를', '에', '의', '와', '과', '으로', '해서', '으로서',
    '하다', '되다', '있다', '없다', '이다', '것', '수', '등', '더', '같다',
    '그리고', '그러나', '또는', '하지만', '고', '도', '또', '및', '중',
    '대한', '한', '해', '를', '되었', '했다'
    # 필요시 계속 추가 가능!
]

# 7. 불용어 제거 함수 정의
def remove_stopwords(tokens):
    return [t for t in tokens if t not in stopwords]

# 8. 전체 데이터에 적용
df_bbc['tokens_no_stop'] = df_bbc['tokens'].apply(remove_stopwords)